import type { Metadata } from "next";
// 1. Noto_Sans_KR 폰트 추가 / Adding Noto_Sans_KR font
import { Geist, Geist_Mono,Noto_Sans_KR } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. 한국어 폰트 설정을 생성합니다. / Create a Korean font setting.
const notoSansKr = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"], 
  // 사용할 굵기 지정 (일반, 미디움, 굵게)
  // Specify the weights to use (normal, medium, bold)
  weight: ["400", "500", "700"], 
});

// 3. 페이지 타이틀 및 설명을 설정합니다. / Set the page title and description.
export const metadata: Metadata = {
  title: "두 번째 Next.js 앱 / Second Next.js App ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} ${notoSansKr.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
